# Generated by Django 6.0 on 2025-12-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=15)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
