# Generated by Django 6.0 on 2025-12-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultation_minutes',
            field=models.IntegerField(default=5),
        ),
    ]
