# Generated by Django 6.0 on 2025-12-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_consultation_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='delay_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
