# Generated by Django 6.0 on 2025-12-27 05:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='status',
        ),
        migrations.AddField(
            model_name='token',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
