# Generated by Django 6.0 on 2025-12-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_remove_token_status_token_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='visit_date',
            field=models.DateField(),
        ),
    ]
