# Generated by Django 6.0 on 2025-12-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_alter_token_token_number_alter_token_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Serving', 'Serving'), ('Done', 'Done')], default='Waiting', max_length=10),
        ),
    ]
