# Generated by Django 6.0 on 2025-12-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_token_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Serving', 'Serving'), ('Done', 'Done'), ('Given', 'Given')], default='Waiting', max_length=10),
        ),
    ]
