# Generated by Django 6.0 on 2025-12-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0005_alter_token_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
